// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Collection struct {
	UserID      pgtype.UUID
	MovieID     int32
	TorrentID   string
	MovieLenght int32
	Progression pgtype.Interval
}
