// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllMoviesInCollection = `-- name: GetAllMoviesInCollection :many
SELECT movie_id, torrent_id, length, progression FROM collection
WHERE user_id=$1
`

type GetAllMoviesInCollectionRow struct {
	MovieID     int32
	TorrentID   string
	Length      int32
	Progression pgtype.Interval
}

func (q *Queries) GetAllMoviesInCollection(ctx context.Context, userID pgtype.UUID) ([]GetAllMoviesInCollectionRow, error) {
	rows, err := q.db.Query(ctx, getAllMoviesInCollection, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMoviesInCollectionRow
	for rows.Next() {
		var i GetAllMoviesInCollectionRow
		if err := rows.Scan(
			&i.MovieID,
			&i.TorrentID,
			&i.Length,
			&i.Progression,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovieInCollection = `-- name: GetMovieInCollection :one
SELECT user_id, movie_id, torrent_id, length, progression FROM collection
WHERE user_id=$1 AND movie_id=$2
`

type GetMovieInCollectionParams struct {
	UserID  pgtype.UUID
	MovieID int32
}

func (q *Queries) GetMovieInCollection(ctx context.Context, arg GetMovieInCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, getMovieInCollection, arg.UserID, arg.MovieID)
	var i Collection
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.TorrentID,
		&i.Length,
		&i.Progression,
	)
	return i, err
}

const userAddMovieToCollection = `-- name: UserAddMovieToCollection :one
INSERT INTO collection (user_id, movie_id, torrent_id, length)
VALUES ($1, $2, $3, $4)
RETURNING user_id, movie_id, torrent_id, length, progression
`

type UserAddMovieToCollectionParams struct {
	UserID    pgtype.UUID
	MovieID   int32
	TorrentID string
	Length    int32
}

func (q *Queries) UserAddMovieToCollection(ctx context.Context, arg UserAddMovieToCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, userAddMovieToCollection,
		arg.UserID,
		arg.MovieID,
		arg.TorrentID,
		arg.Length,
	)
	var i Collection
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.TorrentID,
		&i.Length,
		&i.Progression,
	)
	return i, err
}
