// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movies.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userAddFilmToCollection = `-- name: UserAddFilmToCollection :one
INSERT INTO collection (user_id, movie_id, torrent_id, movie_lenght)
VALUES ($1, $2, $3, $4)
RETURNING user_id, movie_id, torrent_id, movie_lenght, progression
`

type UserAddFilmToCollectionParams struct {
	UserID      pgtype.UUID
	MovieID     int32
	TorrentID   string
	MovieLenght int32
}

func (q *Queries) UserAddFilmToCollection(ctx context.Context, arg UserAddFilmToCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, userAddFilmToCollection,
		arg.UserID,
		arg.MovieID,
		arg.TorrentID,
		arg.MovieLenght,
	)
	var i Collection
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.TorrentID,
		&i.MovieLenght,
		&i.Progression,
	)
	return i, err
}
