// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Languages string

const (
	LanguagesEn Languages = "en"
	LanguagesFr Languages = "fr"
)

func (e *Languages) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Languages(s)
	case string:
		*e = Languages(s)
	default:
		return fmt.Errorf("unsupported scan type for Languages: %T", src)
	}
	return nil
}

type NullLanguages struct {
	Languages Languages
	Valid     bool // Valid is true if Languages is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLanguages) Scan(value interface{}) error {
	if value == nil {
		ns.Languages, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Languages.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLanguages) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Languages), nil
}

type Roles string

const (
	RolesUser  Roles = "user"
	RolesAdmin Roles = "admin"
)

func (e *Roles) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Roles(s)
	case string:
		*e = Roles(s)
	default:
		return fmt.Errorf("unsupported scan type for Roles: %T", src)
	}
	return nil
}

type NullRoles struct {
	Roles Roles
	Valid bool // Valid is true if Roles is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoles) Scan(value interface{}) error {
	if value == nil {
		ns.Roles, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Roles.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoles) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Roles), nil
}

type User struct {
	Uuid     pgtype.UUID
	Username string
	Password string
	Role     Roles
	Language Languages
}
