// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING token_id, user_id, token_hash, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (Refresh, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Refresh
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT token_id, user_id, token_hash, expires_at, revoked_at FROM refresh
WHERE token_hash=$1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (Refresh, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i Refresh
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const setRefreshTokenRevoked = `-- name: SetRefreshTokenRevoked :one
UPDATE refresh
SET revoked_at=$2
WHERE token_hash=$1
RETURNING token_id, user_id, token_hash, expires_at, revoked_at
`

type SetRefreshTokenRevokedParams struct {
	TokenHash string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) SetRefreshTokenRevoked(ctx context.Context, arg SetRefreshTokenRevokedParams) (Refresh, error) {
	row := q.db.QueryRow(ctx, setRefreshTokenRevoked, arg.TokenHash, arg.RevokedAt)
	var i Refresh
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
