// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password)
VALUES ($1, $2)
RETURNING uuid, username, password, role, language
`

type CreateUserParams struct {
	Username string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Language,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT uuid, username, password, role, language FROM users
WHERE uuid = $1
`

func (q *Queries) GetUserByUUID(ctx context.Context, uuid pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, uuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Language,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT uuid, username, password, role, language FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Language,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username=$2, password=$3, role=$4, language=$5
WHERE uuid = $1
RETURNING uuid, username, password, role, language
`

type UpdateUserParams struct {
	Uuid     pgtype.UUID
	Username string
	Password string
	Role     Roles
	Language Languages
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Uuid,
		arg.Username,
		arg.Password,
		arg.Role,
		arg.Language,
	)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Language,
	)
	return i, err
}
